name: Build and Publish utah-header
on: [workflow_dispatch]
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3
      - name: Setup Node ğŸš§
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'  
      - name: NPM Install ğŸ”§
        run: |
          npm install
      - name: NPM header Build ğŸ”§
        run: |
          cd utah-header
          npm run sass-build
          npm run build   
      - name: NPM library Build ğŸ”§
        run: |
          cd library
          npm run sass-build
          npm run build
      - name: NPM Publish ğŸ”§
        run: |
          cd utah-header
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
