name: Build and Publish utah-header
on: [workflow_dispatch]
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ£
        uses: actions/checkout@v3
        with: 
          ref: ${{ github.ref }}
      - name: Setup Node ğŸ”
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'  
      - name: NPM Install ğŸªš
        run: |
          npm install
          - name: NPM header Build ğŸ”¨
          run: |
          npm run buildHeader
      - name: Build Types ğŸªš
        run: |
          npm run buildTypesHeader
      - name: NPM Publish ğŸ 
        run: |
          npm run publishHeader
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
